### ISSUE TITLE
Error 404 Not Found

### ISSUE THREAD

**Issue by robyouyou** [google/device-access-sample-web-app#3]
When trying to sign the project with the correct oauth credentials I receive a 404 error with this message: The requested URL was not found on this server. That’s all we know.

**Comment by jtromo** [comment]
What is the URL that resulted in the 404 error? Are you able to access it manually outside of the web app?

**Comment by robyouyou** [comment]
If I populate the clientID for the initial signIn() function it works just fine.  If not that part of the initial URL is blank and it gives the 404 (at least fix worked).

**Comment by jtromo** [comment]
The clientID is a required field for the Account Linking flow.

**Comment by robyouyou** [comment]
Yup - all good, I just had to read the code (may have been in a readme but I didn't see it).
